# Generated by Django 3.1.3 on 2020-11-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Image',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
