# Generated by Django 3.1.3 on 2020-11-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0002_movies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Image',
        ),
    ]
