# Generated by Django 3.1.3 on 2020-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0006_auto_20201117_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='link1',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='movies',
            name='link7',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
